version: "3.3"
services:

  # Almond
  pyspark:
    image: jupyter/pyspark-notebook
    ports:
      - 8888:8888
      - 4040:4040
      - 4041:4041
    volumes:
      - ./notebooks:/home/jovyan/notebooks
